// frontend/src/app/components/auth-page/auth-page.component.ts
import { Component, Input, Output, EventEmitter, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { lastValueFrom } from 'rxjs';

@Component({
  selector: 'app-auth-page',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './auth-page.component.html'
})
export class AuthPageComponent {
  @Output() authSuccess = new EventEmitter<{ id: number; username: string }>();
  @Output() backToHome = new EventEmitter<void>();

  isLogin = signal(true);
  username = signal('');
  password = signal('');
  error = signal<string | null>(null);
  isLoading = signal(false);

  constructor(private api: ApiService) {}

  setIsLogin(value: boolean): void {
    this.isLogin.set(value);
    this.error.set(null);
  }

  setUsername(value: string): void { this.username.set(value); }
  setPassword(value: string): void { this.password.set(value); }

  async handleSubmit(e: Event): Promise<void> {
    e.preventDefault();
    if (!this.username().trim() || !this.password()) {
      this.error.set('Please fill in all fields.');
      return;
    }
    if (this.password().length < 6) {
      this.error.set('Password must be at least 6 characters.');
      return;
    }

    this.error.set(null);
    this.isLoading.set(true);

    try {
      if (this.isLogin()) {
        const user = await lastValueFrom(this.api.login(this.username(), this.password()));
        this.authSuccess.emit(user);
      } else {
        await lastValueFrom(this.api.register(this.username(), this.password()));
        const user = await lastValueFrom(this.api.login(this.username(), this.password()));
        this.authSuccess.emit(user);
      }
    } catch (err: any) {
      console.error('Auth error:', err);
      this.error.set(err?.error?.error || err?.message || 'Authentication failed. Please try again.');
    } finally {
      this.isLoading.set(false);
    }
  }

  onBackToHome(): void {
    this.backToHome.emit();
  }
}

<div style="display:flex;align-items:center;justify-content:center;min-height:100vh;width:100vw;position:fixed;top:0;left:0;background:radial-gradient(circle at top right,#111827,#030712);font-family:'Outfit','Inter',sans-serif;color:#f3f4f6;z-index:9999;overflow:hidden;">
  <!-- Background Blobs -->
  <div style="position:absolute;border-radius:50%;filter:blur(90px);opacity:0.14;z-index:1;pointer-events:none;top:20%;left:15%;width:350px;height:350px;background:#6366f1;"></div>
  <div style="position:absolute;border-radius:50%;filter:blur(90px);opacity:0.14;z-index:1;pointer-events:none;bottom:20%;right:15%;width:400px;height:400px;background:#14b8a6;"></div>

  <div style="position:relative;z-index:10;width:100%;max-width:430px;padding:2.5rem 2rem;background:rgba(15,23,42,0.45);backdrop-filter:blur(20px);border:1px solid rgba(255,255,255,0.08);border-radius:24px;box-shadow:0 24px 60px rgba(0,0,0,0.6);animation:authFadeIn 0.5s ease;">

    <!-- Logo Section -->
    <div style="display:flex;flex-direction:column;align-items:center;text-align:center;margin-bottom:2rem;">
      <div style="background:linear-gradient(135deg,rgba(99,102,241,0.15),rgba(20,184,166,0.15));padding:0.85rem;border-radius:16px;display:inline-flex;align-items:center;justify-content:center;margin-bottom:1rem;border:1px solid rgba(255,255,255,0.06);">
        <!-- Cpu icon -->
        <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="#818cf8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="16" height="16" x="4" y="4" rx="2"/><rect width="6" height="6" x="9" y="9" rx="1"/><path d="M15 2v2M15 20v2M2 15h2M2 9h2M20 15h2M20 9h2M9 2v2M9 20v2"/></svg>
      </div>
      <h1 style="font-size:1.5rem;font-weight:700;letter-spacing:-0.025em;margin-bottom:0.35rem;background:linear-gradient(to right,#ffffff,#9ca3af);-webkit-background-clip:text;-webkit-text-fill-color:transparent;">FinVertex</h1>
      <p style="font-size:0.8rem;color:#9ca3af;">Transaction Categorizer &amp; Insights Engine</p>
    </div>

    <!-- Tabs -->
    <div style="display:flex;background:rgba(255,255,255,0.03);border-radius:12px;padding:0.25rem;margin-bottom:1.5rem;border:1px solid rgba(255,255,255,0.04);">
      <button
        (click)="setIsLogin(true)"
        [style.background]="isLogin() ? 'rgba(255,255,255,0.08)' : 'none'"
        [style.color]="isLogin() ? '#ffffff' : '#9ca3af'"
        [style.fontWeight]="isLogin() ? '600' : '500'"
        style="flex:1;padding:0.6rem 0;border:none;border-radius:10px;font-size:0.88rem;cursor:pointer;transition:all 0.2s ease;">
        Log In
      </button>
      <button
        (click)="setIsLogin(false)"
        [style.background]="!isLogin() ? 'rgba(255,255,255,0.08)' : 'none'"
        [style.color]="!isLogin() ? '#ffffff' : '#9ca3af'"
        [style.fontWeight]="!isLogin() ? '600' : '500'"
        style="flex:1;padding:0.6rem 0;border:none;border-radius:10px;font-size:0.88rem;cursor:pointer;transition:all 0.2s ease;">
        Register
      </button>
    </div>

    <!-- Error Banner -->
    @if (error()) {
      <div style="display:flex;align-items:center;background:rgba(239,68,68,0.12);border:1px solid rgba(239,68,68,0.25);border-radius:12px;padding:0.75rem 1rem;margin-bottom:1.25rem;font-size:0.82rem;color:#ef4444;">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-right:0.5rem;flex-shrink:0;"><circle cx="12" cy="12" r="10"/><line x1="12" x2="12" y1="8" y2="12"/><line x1="12" x2="12.01" y1="16" y2="16"/></svg>
        <span>{{ error() }}</span>
      </div>
    }

    <!-- Auth Form -->
    <form (ngSubmit)="handleSubmit($event)" style="display:flex;flex-direction:column;gap:1.25rem;">
      <div style="display:flex;flex-direction:column;gap:0.45rem;">
        <label style="font-size:0.8rem;font-weight:600;color:#9ca3af;letter-spacing:0.025em;">Username</label>
        <div style="position:relative;display:flex;align-items:center;">
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#6b7280" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="position:absolute;left:1rem;"><path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
          <input type="text" placeholder="Enter your username"
            [value]="username()"
            (input)="setUsername($any($event.target).value)"
            [disabled]="isLoading()"
            style="width:100%;padding:0.85rem 1rem 0.85rem 2.75rem;background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.06);border-radius:12px;color:#ffffff;font-size:0.9rem;outline:none;" required />
        </div>
      </div>

      <div style="display:flex;flex-direction:column;gap:0.45rem;">
        <label style="font-size:0.8rem;font-weight:600;color:#9ca3af;letter-spacing:0.025em;">Password</label>
        <div style="position:relative;display:flex;align-items:center;">
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#6b7280" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="position:absolute;left:1rem;"><rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
          <input type="password" placeholder="Enter your password (min. 6 chars)"
            [value]="password()"
            (input)="setPassword($any($event.target).value)"
            [disabled]="isLoading()"
            style="width:100%;padding:0.85rem 1rem 0.85rem 2.75rem;background:rgba(255,255,255,0.03);border:1px solid rgba(255,255,255,0.06);border-radius:12px;color:#ffffff;font-size:0.9rem;outline:none;" required />
        </div>
      </div>

      <button type="submit"
        [disabled]="isLoading()"
        style="background:linear-gradient(135deg,#6366f1,#4f46e5);border:none;border-radius:12px;color:#ffffff;padding:0.9rem;cursor:pointer;font-size:0.92rem;display:flex;justify-content:center;align-items:center;gap:0.5rem;margin-top:0.5rem;box-shadow:0 8px 24px rgba(99,102,241,0.3);font-weight:600;">
        @if (isLoading()) {
          <span>Authenticating...</span>
        } @else {
          <span style="display:inline-flex;align-items:center;gap:0.5rem;">
            {{ isLogin() ? 'Sign In to Dashboard' : 'Create Account' }}
            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
          </span>
        }
      </button>
    </form>

    <button (click)="onBackToHome()"
      style="width:100%;margin-top:0.85rem;background:none;border:none;color:#6b7280;font-size:0.85rem;font-weight:500;cursor:pointer;text-align:center;display:block;">
      ← Back to Home
    </button>

    <!-- Features Footer -->
    <div style="display:flex;justify-content:center;gap:1.5rem;margin-top:2rem;border-top:1px solid rgba(255,255,255,0.04);padding-top:1.25rem;">
      <div style="display:flex;align-items:center;gap:0.35rem;font-size:0.74rem;color:#6b7280;">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#818cf8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="m9 12 2 2 4-4"/></svg>
        <span>Encrypted Ledger</span>
      </div>
      <div style="display:flex;align-items:center;gap:0.35rem;font-size:0.74rem;color:#6b7280;">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#818cf8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12V7H5a2 2 0 0 1 0-4h14v4"/><path d="M3 5v14a2 2 0 0 0 2 2h16v-5"/><path d="M18 12a2 2 0 0 0 0 4h4v-4Z"/></svg>
        <span>Multi-Bank Support</span>
      </div>
    </div>
  </div>
</div>

// frontend/src/components/AuthPage.tsx
import React, { useState } from 'react';
import { Lock, User, ArrowRight, ShieldCheck, Cpu, Wallet, AlertCircle } from 'lucide-react';
import { apiService } from '../services/api';

interface AuthPageProps {
  onAuthSuccess: (user: { id: number; username: string }) => void;
  onBackToHome: () => void;
}

export const AuthPage: React.FC<AuthPageProps> = ({ onAuthSuccess, onBackToHome }) => {
  const [isLogin, setIsLogin] = useState(true);
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!username.trim() || !password) {
      setError('Please fill in all fields.');
      return;
    }
    if (password.length < 6) {
      setError('Password must be at least 6 characters.');
      return;
    }

    setError(null);
    setIsLoading(true);

    try {
      if (isLogin) {
        const user = await apiService.login(username, password);
        console.log('Auth: Logged in user:', user);
        onAuthSuccess(user);
      } else {
        const res = await apiService.register(username, password);
        console.log('Auth: Registered user:', res);
        // Automatically login after registration
        const user = await apiService.login(username, password);
        onAuthSuccess(user);
      }
    } catch (err: any) {
      console.error('Auth error:', err);
      setError(err.message || 'Authentication failed. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={styles.container}>
      {/* Background Decorative Blobs */}
      <div style={{ ...styles.blob, ...styles.blob1 }} />
      <div style={{ ...styles.blob, ...styles.blob2 }} />

      <div style={styles.card}>
        {/* Logo Section */}
        <div style={styles.logoSection}>
          <div style={styles.logoContainer}>
            <Cpu size={28} style={styles.logoIcon} />
          </div>
          <h1 style={styles.brandTitle}>FinVertex</h1>
          <p style={styles.brandSubtitle}>Transaction Categorizer & Insights Engine</p>
        </div>

        {/* Mode Selector Tab */}
        <div style={styles.tabs}>
          <button 
            onClick={() => { setIsLogin(true); setError(null); }}
            style={{ ...styles.tab, ...(isLogin ? styles.activeTab : {}) }}
          >
            Log In
          </button>
          <button 
            onClick={() => { setIsLogin(false); setError(null); }}
            style={{ ...styles.tab, ...(!isLogin ? styles.activeTab : {}) }}
          >
            Register
          </button>
        </div>

        {/* Auth Error Banner */}
        {error && (
          <div style={styles.errorBanner}>
            <AlertCircle size={16} style={{ marginRight: '0.5rem', flexShrink: 0 }} />
            <span>{error}</span>
          </div>
        )}

        {/* Auth Form */}
        <form onSubmit={handleSubmit} style={styles.form}>
          <div style={styles.inputGroup}>
            <label style={styles.label}>Username</label>
            <div style={styles.inputWrapper}>
              <User size={18} style={styles.inputIcon} />
              <input
                type="text"
                placeholder="Enter your username"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                style={styles.input}
                disabled={isLoading}
                required
              />
            </div>
          </div>

          <div style={styles.inputGroup}>
            <label style={styles.label}>Password</label>
            <div style={styles.inputWrapper}>
              <Lock size={18} style={styles.inputIcon} />
              <input
                type="password"
                placeholder="Enter your password (min. 6 chars)"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                style={styles.input}
                disabled={isLoading}
                required
              />
            </div>
          </div>

          <button 
            type="submit" 
            style={styles.submitBtn} 
            disabled={isLoading}
          >
            {isLoading ? (
              <span>Authenticating...</span>
            ) : (
              <span style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem', fontWeight: 600 }}>
                {isLogin ? 'Sign In to Dashboard' : 'Create Account'}
                <ArrowRight size={18} />
              </span>
            )}
          </button>
        </form>

        <button 
          onClick={onBackToHome}
          style={{
            width: '100%',
            marginTop: '0.85rem',
            background: 'none',
            border: 'none',
            color: '#6b7280',
            fontSize: '0.85rem',
            fontWeight: 500,
            cursor: 'pointer',
            textAlign: 'center',
            display: 'block',
            transition: 'color 0.2s',
          }}
          onMouseEnter={(e) => (e.currentTarget.style.color = '#9ca3af')}
          onMouseLeave={(e) => (e.currentTarget.style.color = '#6b7280')}
        >
          ← Back to Home
        </button>

        {/* Features Footer */}
        <div style={styles.footer}>
          <div style={styles.featureItem}>
            <ShieldCheck size={14} style={styles.featureIcon} />
            <span>Encrypted Ledger</span>
          </div>
          <div style={styles.featureItem}>
            <Wallet size={14} style={styles.featureIcon} />
            <span>Multi-Bank Support</span>
          </div>
        </div>
      </div>
    </div>
  );
};

const styles: Record<string, React.CSSProperties> = {
  container: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
    width: '100vw',
    position: 'fixed',
    top: 0,
    left: 0,
    background: 'radial-gradient(circle at top right, #111827, #030712)',
    fontFamily: "'Outfit', 'Inter', sans-serif",
    color: '#f3f4f6',
    zIndex: 9999,
    overflow: 'hidden',
  },
  blob: {
    position: 'absolute',
    borderRadius: '50%',
    filter: 'blur(90px)',
    opacity: 0.14,
    zIndex: 1,
    pointerEvents: 'none',
  },
  blob1: {
    top: '20%',
    left: '15%',
    width: '350px',
    height: '350px',
    background: '#6366f1',
  },
  blob2: {
    bottom: '20%',
    right: '15%',
    width: '400px',
    height: '400px',
    background: '#14b8a6',
  },
  card: {
    position: 'relative',
    zIndex: 10,
    width: '100%',
    maxWidth: '430px',
    padding: '2.5rem 2rem',
    background: 'rgba(15, 23, 42, 0.45)',
    backdropFilter: 'blur(20px)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: '24px',
    boxShadow: '0 24px 60px rgba(0, 0, 0, 0.6)',
    animation: 'authFadeIn 0.5s ease',
  },
  logoSection: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    marginBottom: '2rem',
  },
  logoContainer: {
    background: 'linear-gradient(135deg, rgba(99,102,241,0.15), rgba(20,184,166,0.15))',
    padding: '0.85rem',
    borderRadius: '16px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '1rem',
    border: '1px solid rgba(255,255,255,0.06)',
  },
  logoIcon: {
    color: '#818cf8',
  },
  brandTitle: {
    fontSize: '1.5rem',
    fontWeight: 700,
    letterSpacing: '-0.025em',
    marginBottom: '0.35rem',
    background: 'linear-gradient(to right, #ffffff, #9ca3af)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  brandSubtitle: {
    fontSize: '0.8rem',
    color: '#9ca3af',
  },
  tabs: {
    display: 'flex',
    background: 'rgba(255, 255, 255, 0.03)',
    borderRadius: '12px',
    padding: '0.25rem',
    marginBottom: '1.5rem',
    border: '1px solid rgba(255, 255, 255, 0.04)',
  },
  tab: {
    flex: 1,
    padding: '0.6rem 0',
    background: 'none',
    border: 'none',
    borderRadius: '10px',
    color: '#9ca3af',
    fontSize: '0.88rem',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.2s ease',
  },
  activeTab: {
    background: 'rgba(255, 255, 255, 0.08)',
    color: '#ffffff',
    fontWeight: 600,
    boxShadow: '0 4px 12px rgba(0, 0, 0, 0.2)',
  },
  errorBanner: {
    display: 'flex',
    alignItems: 'center',
    background: 'rgba(239, 68, 68, 0.12)',
    border: '1px solid rgba(239, 68, 68, 0.25)',
    borderRadius: '12px',
    padding: '0.75rem 1rem',
    marginBottom: '1.25rem',
    fontSize: '0.82rem',
    color: '#ef4444',
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.45rem',
  },
  label: {
    fontSize: '0.8rem',
    fontWeight: 600,
    color: '#9ca3af',
    letterSpacing: '0.025em',
  },
  inputWrapper: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
  },
  inputIcon: {
    position: 'absolute',
    left: '1rem',
    color: '#6b7280',
  },
  input: {
    width: '100%',
    padding: '0.85rem 1rem 0.85rem 2.75rem',
    background: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid rgba(255, 255, 255, 0.06)',
    borderRadius: '12px',
    color: '#ffffff',
    fontSize: '0.9rem',
    outline: 'none',
    transition: 'all 0.2s ease',
  },
  submitBtn: {
    background: 'linear-gradient(135deg, #6366f1, #4f46e5)',
    border: 'none',
    borderRadius: '12px',
    color: '#ffffff',
    padding: '0.9rem',
    cursor: 'pointer',
    fontSize: '0.92rem',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    transition: 'all 0.2s ease',
    marginTop: '0.5rem',
    boxShadow: '0 8px 24px rgba(99, 102, 241, 0.3)',
  },
  footer: {
    display: 'flex',
    justifyContent: 'center',
    gap: '1.5rem',
    marginTop: '2rem',
    borderTop: '1px solid rgba(255, 255, 255, 0.04)',
    paddingTop: '1.25rem',
  },
  featureItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.35rem',
    fontSize: '0.74rem',
    color: '#6b7280',
  },
  featureIcon: {
    color: '#818cf8',
  },
};
