// frontend/src/app/components/dashboard/dashboard.component.ts
import { Component, Input, OnChanges, SimpleChanges, ChangeDetectionStrategy } from '@angular/core';

import { Transaction } from '../../models/transaction.model';

interface SpendingCategory {
  category: string;
  amount: number;
  percentage: number;
  color: string;
}

interface Spike {
  category: string;
  amount: number;
  description: string;
  ratio: number;
}

@Component({
    selector: 'app-dashboard',
    imports: [],
    changeDetection: ChangeDetectionStrategy.Eager,
    templateUrl: './dashboard.component.html'
})
export class DashboardComponent implements OnChanges {
  @Input() transactions: Transaction[] = [];
  @Input() linkedBanks: string[] = [];

  totalIncome = 0;
  totalExpense = 0;
  anomalies: Transaction[] = [];
  sortedCategories: SpendingCategory[] = [];
  spikes: Spike[] = [];
  budgetTip = 'Connect a bank feed or add manual transactions to get personalized budget insights.';
  duplicateCount = 0;

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['transactions'] || changes['linkedBanks']) {
      this.recalculate();
    }
  }

  recalculate(): void {
    const transactions = this.transactions;

    const incomeTrans = transactions.filter(t => t.category === 'Income');
    this.totalIncome = incomeTrans.reduce((sum, t) => sum + (t.amount || 0), 0);

    const expenses = transactions.filter(t => t.category !== 'Income');
    this.totalExpense = expenses.reduce((sum, t) => {
      const isCredit = t.type === 'CREDIT';
      return sum + (isCredit ? -1 : 1) * (t.amount || 0);
    }, 0);

    this.anomalies = transactions.filter(t => t.anomalyStatus && t.anomalyStatus !== 'NONE');
    this.duplicateCount = this.anomalies.filter(a => a.anomalyStatus === 'DUPLICATE_SUSPECT').length;

    const categoryMap: Record<string, number> = {};
    expenses.forEach(t => {
      const isCredit = t.type === 'CREDIT';
      categoryMap[t.category] = (categoryMap[t.category] || 0) + (isCredit ? -1 : 1) * (t.amount || 0);
    });

    this.sortedCategories = Object.entries(categoryMap)
      .sort((a, b) => b[1] - a[1])
      .map(([category, amount]) => ({
        category,
        amount,
        percentage: this.totalExpense > 0 ? (amount / this.totalExpense) * 100 : 0,
        color: this.getCategoryColor(category)
      }));

    // Spikes calculation
    this.spikes = [];
    if (transactions.length > 0) {
      const categoryTransactions: Record<string, Transaction[]> = {};
      expenses.forEach(t => {
        const cat = t.category || 'Uncategorized';
        if (!categoryTransactions[cat]) categoryTransactions[cat] = [];
        categoryTransactions[cat].push(t);
      });

      Object.entries(categoryTransactions).forEach(([category, list]) => {
        if (list.length < 3) return;
        const amounts = list.map(t => t.amount || 0);
        const maxAmount = Math.max(...amounts);
        const maxTx = list.find(t => t.amount === maxAmount)!;
        const otherAmounts = amounts.filter(a => a !== maxAmount);
        if (otherAmounts.length === 0) return;
        const avg = otherAmounts.reduce((s, a) => s + a, 0) / otherAmounts.length;
        if (avg > 0 && maxAmount > avg * 1.8 && maxAmount > 1000) {
          this.spikes.push({ category, amount: maxAmount, description: maxTx.description || 'Merchant', ratio: Math.round((maxAmount / avg) * 10) / 10 });
        }
      });
      this.spikes.sort((a, b) => b.ratio - a.ratio);
    }

    // Budget tip
    if (transactions.length > 0 && this.sortedCategories.length > 0) {
      const top = this.sortedCategories[0];
      const topPercent = this.totalExpense > 0 ? Math.round((top.amount / this.totalExpense) * 100) : 0;
      const catTotal = top.amount.toLocaleString(undefined, { maximumFractionDigits: 0 });
      const cat = top.category.toLowerCase();
      if (cat === 'dining') {
        this.budgetTip = `You spent ${topPercent}% of your budget on Dining (₹${catTotal}). Preparing more meals at home could save you a significant amount this month.`;
      } else if (cat === 'shopping') {
        this.budgetTip = `Shopping is your highest variable cost at ${topPercent}% of your budget (₹${catTotal}). Setting a weekly limit could boost your savings.`;
      } else if (cat === 'rent' || cat === 'bills') {
        this.budgetTip = `Fixed costs (${top.category}) represent ${topPercent}% of your budget (₹${catTotal}). Focus on optimizing variable costs (Dining/Shopping) to boost savings.`;
      } else {
        this.budgetTip = `${top.category} is your largest expense category this month, representing ${topPercent}% of total expenses (₹${catTotal}).`;
      }
    } else if (transactions.length > 0) {
      this.budgetTip = `Your total expenses are ₹${this.totalExpense.toLocaleString(undefined, { maximumFractionDigits: 0 })}. Ask the chatbot "Help me create a savings plan" to optimize your budget.`;
    } else {
      this.budgetTip = 'Connect a bank feed or add manual transactions to get personalized budget insights.';
    }
  }

  getCategoryColor(category: string): string {
    switch (category.toLowerCase()) {
      case 'dining': return 'var(--color-warning)';
      case 'grocery': return 'var(--color-success)';
      case 'transportation': return 'var(--color-accent)';
      case 'rent': return 'var(--color-primary)';
      case 'bills': return '#a78bfa';
      case 'shopping': return '#f472b6';
      case 'medical': return '#f87171';
      default: return 'var(--text-muted)';
    }
  }

  formatCurrency(amount: number, opts?: Intl.NumberFormatOptions): string {
    return amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2, ...opts });
  }

  linkedBankCount(): string {
    return `${this.linkedBanks.length} Bank${this.linkedBanks.length !== 1 ? 's' : ''}`;
  }
}

<div style="display:flex;flex-direction:column;gap:1.5rem;">

  <!-- Stat Row -->
  <div class="stats-row">
    <div class="stat-card">
      <div class="stat-icon primary">
        <!-- TrendingDown -->
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 17 13.5 8.5 8.5 13.5 2 7"/><polyline points="16 17 22 17 22 11"/></svg>
      </div>
      <div class="stat-info">
        <span class="stat-label">Total Expenses</span>
        <span class="stat-value">₹{{ formatCurrency(totalExpense) }}</span>
      </div>
    </div>

    <div class="stat-card">
      <div class="stat-icon success">
        <!-- TrendingUp -->
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 7 13.5 15.5 8.5 10.5 2 17"/><polyline points="16 7 22 7 22 13"/></svg>
      </div>
      <div class="stat-info">
        <span class="stat-label">Total Income</span>
        <span class="stat-value">₹{{ formatCurrency(totalIncome) }}</span>
      </div>
    </div>

    <div class="stat-card">
      <div class="stat-icon danger">
        <!-- AlertTriangle -->
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><path d="M12 9v4"/><path d="M12 17h.01"/></svg>
      </div>
      <div class="stat-info">
        <span class="stat-label">Anomalies</span>
        <span class="stat-value" [style.color]="anomalies.length > 0 ? 'var(--color-danger)' : 'var(--text-primary)'">
          {{ anomalies.length }} Flagged
        </span>
      </div>
    </div>

    <div class="stat-card">
      <div class="stat-icon accent">
        <!-- Building -->
        <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="16" height="20" x="4" y="2" rx="2" ry="2"/><path d="M9 22v-4h6v4"/><path d="M8 6h.01"/><path d="M16 6h.01"/><path d="M12 6h.01"/><path d="M12 10h.01"/><path d="M12 14h.01"/><path d="M16 10h.01"/><path d="M16 14h.01"/><path d="M8 10h.01"/><path d="M8 14h.01"/></svg>
      </div>
      <div class="stat-info">
        <span class="stat-label">Linked Feeds</span>
        <span class="stat-value">{{ linkedBankCount() }}</span>
      </div>
    </div>
  </div>

  <!-- Anomaly Alerts -->
  @if (anomalies.length > 0) {
    <div class="card" style="border-color:rgba(244,63,94,0.3);background:rgba(244,63,94,0.05);border-left:4px solid var(--color-danger);">
      <h3 style="font-size:1rem;font-weight:700;display:flex;align-items:center;gap:0.5rem;margin-bottom:0.75rem;color:var(--color-danger);">
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><path d="M12 9v4"/><path d="M12 17h.01"/></svg>
        Financial Anomaly Alerts Detected
      </h3>
      <div style="display:flex;flex-direction:column;gap:0.5rem;">
        @for (t of anomalies; track t.id) {
          <div style="display:flex;justify-content:space-between;align-items:center;padding:0.5rem 0.75rem;background:rgba(15,23,42,0.4);border:1px solid rgba(244,63,94,0.1);border-radius:6px;font-size:0.85rem;">
            <div>
              <span style="font-weight:700;color:#fff;">{{ t.description }}</span> -
              <span style="color:var(--text-secondary);margin-left:0.25rem;">{{ t.anomalyDescription }}</span>
            </div>
            <span style="font-weight:800;color:var(--color-danger);white-space:nowrap;">₹{{ t.amount }}</span>
          </div>
        }
      </div>
    </div>
  }

  <!-- Category Breakdown + AI Summary Grid -->
  <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:1.5rem;">

    <!-- Category Breakdown -->
    <div class="card">
      <h3 style="font-size:1rem;font-weight:700;margin-bottom:1rem;">Spending by Category</h3>
      @if (sortedCategories.length === 0) {
        <p style="font-size:0.85rem;color:var(--text-muted);text-align:center;padding:2rem 0;">
          No expense data available. Sync your accounts to populate categories.
        </p>
      } @else {
        <div style="display:flex;flex-direction:column;gap:1rem;">
          @for (cat of sortedCategories; track cat.category) {
            <div style="display:flex;flex-direction:column;gap:0.35rem;">
              <div style="display:flex;justify-content:space-between;font-size:0.85rem;">
                <span style="font-weight:600;">{{ cat.category }}</span>
                <span style="font-weight:700;">
                  ₹{{ cat.amount.toLocaleString() }}
                  <span style="font-size:0.75rem;color:var(--text-muted);font-weight:400;margin-left:0.35rem;">({{ cat.percentage.toFixed(0) }}%)</span>
                </span>
              </div>
              <div style="width:100%;height:8px;background:rgba(255,255,255,0.05);border-radius:4px;overflow:hidden;">
                <div [style.width]="cat.percentage + '%'" [style.background]="cat.color" style="height:100%;border-radius:4px;"></div>
              </div>
            </div>
          }
        </div>
      }
    </div>

    <!-- AI Budget Analysis Card -->
    <div class="card" style="background:linear-gradient(135deg,rgba(99,102,241,0.15),rgba(20,184,166,0.05));">
      <h3 style="font-size:1rem;font-weight:700;margin-bottom:0.5rem;color:var(--color-accent);">📊 FinVertex Spending Analysis</h3>
      <p style="font-size:0.85rem;color:var(--text-secondary);line-height:1.5;margin-bottom:1rem;">
        Based on your active transactions and bank feeds, the FinVertex assistant can analyze anomalous patterns or recommend savings strategies.
      </p>
      <div style="display:flex;flex-direction:column;gap:0.75rem;font-size:0.825rem;color:var(--text-primary);">
        <div style="background:rgba(15,23,42,0.4);padding:0.75rem;border-radius:8px;border:1px solid var(--border-color);">
          @if (transactions.length === 0) {
            <span>Connect a bank feed or add manual entries to scan for duplicate charges.</span>
          } @else if (duplicateCount > 0) {
            <span><strong>⚠️ Suspected Duplicate Charges:</strong> {{ duplicateCount }} items found. Ask the chatbot: <em>"How do I resolve duplicate charges?"</em> to inspect.</span>
          } @else {
            <span><strong>✓ No Duplicate Charges:</strong> Your accounts look clean! No duplicate billing events suspected.</span>
          }
        </div>
        <div style="background:rgba(15,23,42,0.4);padding:0.75rem;border-radius:8px;border:1px solid var(--border-color);">
          @if (transactions.length === 0) {
            <span>No anomalies detected. Your transactions are within standard parameters.</span>
          } @else if (spikes.length > 0) {
            <span><strong>🚨 {{ spikes[0].category }} Spike:</strong> You had a high {{ spikes[0].category }} expense of ₹{{ spikes[0].amount.toLocaleString() }} ({{ spikes[0].description }}) recently. That is {{ spikes[0].ratio }}x higher than your average spending.</span>
          } @else {
            <span><strong>✓ Spending Spikes:</strong> No sudden spending spikes detected this week. Your transactions are within normal limits.</span>
          }
        </div>
        <div style="background:rgba(15,23,42,0.4);padding:0.75rem;border-radius:8px;border:1px solid var(--border-color);">
          <strong>💡 Budget Tip:</strong> {{ budgetTip }}
        </div>
      </div>
    </div>
  </div>
</div>

// frontend/src/components/Dashboard.tsx
import React from 'react';
import { AlertTriangle, TrendingDown, TrendingUp, Building } from 'lucide-react';
import type { Transaction } from '../services/api';

interface DashboardProps {
  transactions: Transaction[];
  linkedBanks: string[];
}

export const Dashboard: React.FC<DashboardProps> = ({ transactions, linkedBanks }) => {
  // Calculate aggregate metrics
  const expenses = transactions.filter(t => t.category !== 'Income');
  const totalExpense = expenses.reduce((sum, t) => sum + (t.amount || 0), 0);
  
  const incomeTrans = transactions.filter(t => t.category === 'Income');
  const totalIncome = incomeTrans.reduce((sum, t) => sum + (t.amount || 0), 0);
  
  const anomalies = transactions.filter(t => t.anomalyStatus && t.anomalyStatus !== 'NONE');

  // Calculate category aggregates
  const categoryMap: Record<string, number> = {};
  expenses.forEach(t => {
    categoryMap[t.category] = (categoryMap[t.category] || 0) + (t.amount || 0);
  });

  const sortedCategories = Object.entries(categoryMap)
    .sort((a, b) => b[1] - a[1]);

  // Calculate dynamic spikes
  const spikes: Array<{ category: string; amount: number; description: string; ratio: number }> = [];
  if (transactions.length > 0) {
    const categoryTransactions: Record<string, Transaction[]> = {};
    expenses.forEach(t => {
      const cat = t.category || 'Uncategorized';
      if (!categoryTransactions[cat]) {
        categoryTransactions[cat] = [];
      }
      categoryTransactions[cat].push(t);
    });

    Object.entries(categoryTransactions).forEach(([category, list]) => {
      if (list.length < 3) return; // need a baseline to compute average
      const amounts = list.map(t => t.amount || 0);
      const maxAmount = Math.max(...amounts);
      const maxTx = list.find(t => t.amount === maxAmount)!;
      
      const otherAmounts = amounts.filter(a => a !== maxAmount);
      if (otherAmounts.length === 0) return;
      const avg = otherAmounts.reduce((sum, a) => sum + a, 0) / otherAmounts.length;
      
      if (avg > 0 && maxAmount > avg * 1.8 && maxAmount > 1000) {
        spikes.push({
          category,
          amount: maxAmount,
          description: maxTx.description || 'Merchant',
          ratio: Math.round((maxAmount / avg) * 10) / 10
        });
      }
    });
  }

  // Sort spikes to display the most significant ratio first
  spikes.sort((a, b) => b.ratio - a.ratio);

  // Generate dynamic budget tip
  let budgetTip = 'Connect a bank feed or add manual transactions to get personalized budget insights.';
  if (transactions.length > 0 && sortedCategories.length > 0) {
    const topCategory = sortedCategories[0];
    const topPercent = totalExpense > 0 ? Math.round((topCategory[1] / totalExpense) * 100) : 0;
    const catName = topCategory[0];
    const catTotal = topCategory[1].toLocaleString(undefined, { maximumFractionDigits: 0 });

    if (catName.toLowerCase() === 'dining') {
      budgetTip = `You spent ${topPercent}% of your budget on Dining (₹${catTotal}). Preparing more meals at home could save you a significant amount this month.`;
    } else if (catName.toLowerCase() === 'shopping') {
      budgetTip = `Shopping is your highest variable cost at ${topPercent}% of your budget (₹${catTotal}). Setting a weekly limit could boost your savings.`;
    } else if (catName.toLowerCase() === 'rent' || catName.toLowerCase() === 'bills') {
      budgetTip = `Fixed costs (${catName}) represent ${topPercent}% of your budget (₹${catTotal}). Focus on optimizing variable costs (Dining/Shopping) to boost savings.`;
    } else {
      budgetTip = `${catName} is your largest expense category this month, representing ${topPercent}% of total expenses (₹${catTotal}).`;
    }
  } else if (transactions.length > 0) {
    budgetTip = `Your total expenses are ₹${totalExpense.toLocaleString(undefined, { maximumFractionDigits: 0 })}. Ask the chatbot "Help me create a savings plan" to optimize your budget.`;
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      
      {/* Stat Row */}
      <div className="stats-row">
        <div className="stat-card">
          <div className="stat-icon primary">
            <TrendingDown size={22} />
          </div>
          <div className="stat-info">
            <span className="stat-label">Total Expenses</span>
            <span className="stat-value">₹{totalExpense.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon success">
            <TrendingUp size={22} />
          </div>
          <div className="stat-info">
            <span className="stat-label">Total Income</span>
            <span className="stat-value">₹{totalIncome.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon danger">
            <AlertTriangle size={22} />
          </div>
          <div className="stat-info">
            <span className="stat-label">Anomalies</span>
            <span className="stat-value" style={{ color: anomalies.length > 0 ? 'var(--color-danger)' : '#fff' }}>
              {anomalies.length} Flagged
            </span>
          </div>
        </div>

        <div className="stat-card">
          <div className="stat-icon accent">
            <Building size={22} />
          </div>
          <div className="stat-info">
            <span className="stat-label">Linked Feeds</span>
            <span className="stat-value">{linkedBanks.length} Bank{linkedBanks.length !== 1 ? 's' : ''}</span>
          </div>
        </div>
      </div>

      {/* Critical Anomalies Alerts */}
      {anomalies.length > 0 && (
        <div 
          className="card" 
          style={{ 
            borderColor: 'rgba(244, 63, 94, 0.3)', 
            background: 'rgba(244, 63, 94, 0.05)',
            borderLeft: '4px solid var(--color-danger)'
          }}
        >
          <h3 style={{ fontSize: '1rem', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.75rem', color: 'var(--color-danger)' }}>
            <AlertTriangle size={18} /> Financial Anomaly Alerts Detected
          </h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
            {anomalies.map(t => (
              <div 
                key={t.id} 
                style={{ 
                  display: 'flex', 
                  justifyContent: 'space-between', 
                  alignItems: 'center', 
                  padding: '0.5rem 0.75rem', 
                  background: 'rgba(15, 23, 42, 0.4)', 
                  border: '1px solid rgba(244, 63, 94, 0.1)',
                  borderRadius: '6px',
                  fontSize: '0.85rem' 
                }}
              >
                <div>
                  <span style={{ fontWeight: 700, color: '#fff' }}>{t.description}</span> - 
                  <span style={{ color: 'var(--text-secondary)', marginLeft: '0.25rem' }}>{t.anomalyDescription}</span>
                </div>
                <span style={{ fontWeight: 800, color: 'var(--color-danger)', whiteSpace: 'nowrap' }}>
                  ₹{t.amount}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Grid: Category Breakdown and AI Summary */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '1.5rem' }}>
        
        {/* Category Breakdown (Custom visual graph cards) */}
        <div className="card">
          <h3 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: '1rem' }}>Spending by Category</h3>
          
          {sortedCategories.length === 0 ? (
            <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', textAlign: 'center', padding: '2rem 0' }}>
              No expense data available. Sync your accounts to populate categories.
            </p>
          ) : (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              {sortedCategories.map(([category, amount]) => {
                const percentage = totalExpense > 0 ? (amount / totalExpense) * 100 : 0;
                return (
                  <div key={category} style={{ display: 'flex', flexDirection: 'column', gap: '0.35rem' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.85rem' }}>
                      <span style={{ fontWeight: 600 }}>{category}</span>
                      <span style={{ fontWeight: 700 }}>
                        ₹{amount.toLocaleString()} 
                        <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', fontWeight: 400, marginLeft: '0.35rem' }}>
                          ({percentage.toFixed(0)}%)
                        </span>
                      </span>
                    </div>
                    {/* Visual Progress Bar */}
                    <div style={{ width: '100%', height: '8px', background: 'rgba(255,255,255,0.05)', borderRadius: '4px', overflow: 'hidden' }}>
                      <div 
                        className={`bar-${category.toLowerCase()}`}
                        style={{ 
                          height: '100%', 
                          width: `${percentage}%`,
                          borderRadius: '4px',
                          background: getCategoryColor(category)
                        }}
                      ></div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Dynamic Budget Coach Card */}
        <div className="card" style={{ background: 'linear-gradient(135deg, rgba(99, 102, 241, 0.15), rgba(20, 184, 166, 0.05))' }}>
          <h3 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: '0.5rem', color: 'var(--color-accent)' }}>
            📊 FinVertex Spending Analysis
          </h3>
          <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', lineHeight: '1.5', marginBottom: '1rem' }}>
            Based on your active transactions and bank feeds, the FinVertex assistant can analyze anomalous patterns or recommend savings strategies.
          </p>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', fontSize: '0.825rem', color: 'var(--text-primary)' }}>
            {/* Duplicate Charges */}
            <div style={{ background: 'rgba(15, 23, 42, 0.4)', padding: '0.75rem', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
              {transactions.length === 0 ? (
                <span>Connect a bank feed or add manual entries to scan for duplicate charges.</span>
              ) : anomalies.filter(a => a.anomalyStatus === 'DUPLICATE_SUSPECT').length > 0 ? (
                <span>
                  <strong>⚠️ Suspected Duplicate Charges:</strong> {anomalies.filter(a => a.anomalyStatus === 'DUPLICATE_SUSPECT').length} items found. Ask the chatbot: <em>"How do I resolve duplicate charges?"</em> to inspect.
                </span>
              ) : (
                <span><strong>✓ No Duplicate Charges:</strong> Your accounts look clean! No duplicate billing events suspected.</span>
              )}
            </div>
            
            {/* Spikes */}
            <div style={{ background: 'rgba(15, 23, 42, 0.4)', padding: '0.75rem', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
              {transactions.length === 0 ? (
                <span>No anomalies detected. Your transactions are within standard parameters.</span>
              ) : spikes.length > 0 ? (
                <span>
                  <strong>🚨 {spikes[0].category} Spike:</strong> You had a high {spikes[0].category} expense of ₹{spikes[0].amount.toLocaleString()} ({spikes[0].description}) recently. That is {spikes[0].ratio}x higher than your average {spikes[0].category} spending.
                </span>
              ) : (
                <span><strong>✓ Spending Spikes:</strong> No sudden spending spikes detected this week. Your transactions are within normal limits.</span>
              )}
            </div>

            {/* Budget Tip */}
            <div style={{ background: 'rgba(15, 23, 42, 0.4)', padding: '0.75rem', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
              <strong>💡 Budget Tip:</strong> {budgetTip}
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};

// Helper for dynamic colors matching CSS badges
function getCategoryColor(category: string): string {
  switch (category.toLowerCase()) {
    case 'dining': return 'var(--color-warning)';
    case 'grocery': return 'var(--color-success)';
    case 'transportation': return 'var(--color-accent)';
    case 'rent': return 'var(--color-primary)';
    case 'bills': return '#a78bfa';
    case 'shopping': return '#f472b6';
    case 'medical': return '#f87171';
    default: return 'var(--text-muted)';
  }
}
