// frontend/src/app/components/plaid-sandbox/plaid-sandbox.component.ts
import { Component, Input, Output, EventEmitter, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface Bank { name: string; color: string; }

@Component({
  selector: 'app-plaid-sandbox',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './plaid-sandbox.component.html'
})
export class PlaidSandboxComponent {
  @Input() isOpen = false;
  @Output() closeModal = new EventEmitter<void>();
  @Output() success = new EventEmitter<string>();

  step = signal<1 | 2 | 3>(1);
  selectedBank = signal('');
  username = signal('');
  password = signal('');

  banks: Bank[] = [
    { name: 'Chase Bank', color: '#115ec3' },
    { name: 'Bank of America', color: '#dc143c' },
    { name: 'Wells Fargo', color: '#d31115' },
    { name: 'Citi Bank', color: '#004b87' }
  ];

  handleSelectBank(bankName: string): void {
    this.selectedBank.set(bankName);
    this.step.set(2);
  }

  handleLoginSubmit(e: Event): void {
    e.preventDefault();
    if (!this.username() || !this.password()) return;
    this.step.set(3);
    setTimeout(() => {
      this.success.emit(this.selectedBank());
      this.closeModal.emit();
      this.step.set(1);
      this.selectedBank.set('');
      this.username.set('');
      this.password.set('');
    }, 3000);
  }

  onClose(): void { this.closeModal.emit(); }
  goBack(): void { this.step.set(1); }
}

@if (isOpen) {
  <div class="modal-overlay">
    <div class="modal-content" style="max-width:400px;padding:1.5rem;">
      <button (click)="onClose()" class="btn btn-secondary btn-icon" style="position:absolute;top:1rem;right:1rem;padding:0.25rem;border-radius:50%;">
        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
      </button>

      <!-- Step 1: Select Bank -->
      @if (step() === 1) {
        <div>
          <div style="text-align:center;margin-bottom:1.5rem;">
            <div style="background:rgba(99,102,241,0.1);color:var(--color-primary);width:56px;height:56px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;margin-bottom:0.75rem;">
              <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="m9 12 2 2 4-4"/></svg>
            </div>
            <h2 style="font-size:1.25rem;font-weight:700;margin-bottom:0.25rem;">Link Bank Account</h2>
            <p style="font-size:0.8rem;color:var(--text-secondary);">Secured by Plaid Sandbox protocol</p>
          </div>
          <p style="font-size:0.85rem;color:var(--text-muted);margin-bottom:1rem;text-align:center;">Select a mock financial institution to simulate syncing your transaction data.</p>
          <div style="display:flex;flex-direction:column;gap:0.5rem;">
            @for (bank of banks; track bank.name) {
              <button (click)="handleSelectBank(bank.name)" class="btn btn-secondary" style="justify-content:space-between;padding:0.9rem 1rem;width:100%;">
                <div style="display:flex;align-items:center;gap:0.75rem;">
                  <div [style.background-color]="bank.color" style="width:12px;height:12px;border-radius:50%;"></div>
                  <span>{{ bank.name }}</span>
                </div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--text-muted)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
              </button>
            }
          </div>
          <div style="display:flex;align-items:center;justify-content:center;gap:0.35rem;margin-top:1.5rem;color:var(--text-muted);font-size:0.75rem;">
            <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="11" x="3" y="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
            <span>End-to-end 256-bit encryption</span>
          </div>
        </div>
      }

      <!-- Step 2: Login to Bank -->
      @if (step() === 2) {
        <form (ngSubmit)="handleLoginSubmit($event)">
          <div style="text-align:center;margin-bottom:1.5rem;">
            <div style="background:rgba(20,184,166,0.1);color:var(--color-accent);width:48px;height:48px;border-radius:50%;display:inline-flex;align-items:center;justify-content:center;margin-bottom:0.75rem;">
              <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="16" height="20" x="4" y="2" rx="2" ry="2"/><path d="M9 22v-4h6v4"/><path d="M8 6h.01"/><path d="M16 6h.01"/><path d="M12 6h.01"/><path d="M12 10h.01"/><path d="M12 14h.01"/><path d="M16 10h.01"/><path d="M16 14h.01"/><path d="M8 10h.01"/><path d="M8 14h.01"/></svg>
            </div>
            <h2 style="font-size:1.25rem;font-weight:700;margin-bottom:0.25rem;">Login to {{ selectedBank() }}</h2>
            <p style="font-size:0.8rem;color:var(--text-secondary);">Plaid Sandbox Credentials Required</p>
          </div>
          <div style="background:rgba(245,158,11,0.1);border:1px solid rgba(245,158,11,0.2);padding:0.75rem;border-radius:8px;margin-bottom:1.25rem;font-size:0.75rem;color:var(--color-warning);">
            <strong>Sandbox Hint:</strong> Enter username <code>user_good</code> and password <code>mfa_device</code> to authorize.
          </div>
          <div style="display:flex;flex-direction:column;gap:1rem;margin-bottom:1.5rem;">
            <div>
              <label style="display:block;font-size:0.8rem;color:var(--text-secondary);margin-bottom:0.35rem;font-weight:500;">Username</label>
              <input type="text" placeholder="e.g. user_good" [value]="username()" (input)="username.set($any($event.target).value)" class="filter-input" style="width:100%;padding:0.75rem;" required />
            </div>
            <div>
              <label style="display:block;font-size:0.8rem;color:var(--text-secondary);margin-bottom:0.35rem;font-weight:500;">Password</label>
              <input type="password" placeholder="e.g. mfa_device" [value]="password()" (input)="password.set($any($event.target).value)" class="filter-input" style="width:100%;padding:0.75rem;" required />
            </div>
          </div>
          <div style="display:flex;gap:0.5rem;">
            <button type="button" (click)="goBack()" class="btn btn-secondary" style="flex:1;">Back</button>
            <button type="submit" class="btn btn-primary" style="flex:2;">Authorize Link</button>
          </div>
        </form>
      }

      <!-- Step 3: Connecting -->
      @if (step() === 3) {
        <div style="text-align:center;padding:2rem 1rem;">
          <div style="margin-bottom:1.5rem;">
            <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="var(--color-primary)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="spinning" style="animation:spin 1.5s linear infinite;"><path d="M21 12a9 9 0 1 1-6.219-8.56"/></svg>
          </div>
          <h3 style="font-size:1.1rem;font-weight:700;margin-bottom:0.5rem;">Connecting to {{ selectedBank() }}...</h3>
          <p style="font-size:0.8rem;color:var(--text-secondary);">Retrieving accounts and authorization tokens. Auto-syncing bank feed transactions into your database.</p>
        </div>
      }
    </div>
  </div>
}

// frontend/src/components/PlaidSandbox.tsx
import React, { useState } from 'react';
import { X, ShieldCheck, Lock, Building, ArrowRight, Loader2 } from 'lucide-react';

interface PlaidSandboxProps {
  isOpen: boolean;
  onClose: () => void;
  onSuccess: (bankName: string) => void;
}

export const PlaidSandbox: React.FC<PlaidSandboxProps> = ({ isOpen, onClose, onSuccess }) => {
  const [step, setStep] = useState<1 | 2 | 3>(1);
  const [selectedBank, setSelectedBank] = useState<string>('');
  const [username, setUsername] = useState<string>('');
  const [password, setPassword] = useState<string>('');

  if (!isOpen) return null;

  const banks = [
    { name: 'Chase Bank', color: '#115ec3' },
    { name: 'Bank of America', color: '#dc143c' },
    { name: 'Wells Fargo', color: '#d31115' },
    { name: 'Citi Bank', color: '#004b87' }
  ];

  const handleSelectBank = (bankName: string) => {
    setSelectedBank(bankName);
    setStep(2);
  };

  const handleLoginSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!username || !password) return;
    
    setStep(3);
    
    // Simulate Plaid MFA/Authentication Connection
    setTimeout(() => {
      onSuccess(selectedBank);
      onClose();
      // Reset state
      setStep(1);
      setSelectedBank('');
      setUsername('');
      setPassword('');
    }, 3000);
  };

  return (
    <div className="modal-overlay">
      <div className="modal-content" style={{ maxWidth: '400px', padding: '1.5rem' }}>
        <button 
          onClick={onClose} 
          className="btn btn-secondary btn-icon" 
          style={{ position: 'absolute', top: '1rem', right: '1rem', padding: '0.25rem', borderRadius: '50%' }}
        >
          <X size={18} />
        </button>

        {step === 1 && (
          <div>
            <div style={{ textAlign: 'center', marginBottom: '1.5rem' }}>
              <div style={{ background: 'rgba(99, 102, 241, 0.1)', color: 'var(--color-primary)', width: '56px', height: '56px', borderRadius: '50%', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', marginBottom: '0.75rem' }}>
                <ShieldCheck size={28} />
              </div>
              <h2 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '0.25rem' }}>Link Bank Account</h2>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Secured by Plaid Sandbox protocol</p>
            </div>

            <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '1rem', textAlign: 'center' }}>
              Select a mock financial institution to simulate syncing your transaction data.
            </p>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              {banks.map((bank) => (
                <button
                  key={bank.name}
                  onClick={() => handleSelectBank(bank.name)}
                  className="btn btn-secondary"
                  style={{ justifyContent: 'space-between', padding: '0.9rem 1rem', width: '100%' }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
                    <div style={{ width: '12px', height: '12px', borderRadius: '50%', backgroundColor: bank.color }}></div>
                    <span>{bank.name}</span>
                  </div>
                  <ArrowRight size={16} style={{ color: 'var(--text-muted)' }} />
                </button>
              ))}
            </div>
            
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.35rem', marginTop: '1.5rem', color: 'var(--text-muted)', fontSize: '0.75rem' }}>
              <Lock size={12} />
              <span>End-to-end 256-bit encryption</span>
            </div>
          </div>
        )}

        {step === 2 && (
          <form onSubmit={handleLoginSubmit}>
            <div style={{ textAlign: 'center', marginBottom: '1.5rem' }}>
              <div style={{ background: 'rgba(20, 184, 166, 0.1)', color: 'var(--color-accent)', width: '48px', height: '48px', borderRadius: '50%', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', marginBottom: '0.75rem' }}>
                <Building size={22} />
              </div>
              <h2 style={{ fontSize: '1.25rem', fontWeight: 700, marginBottom: '0.25rem' }}>Login to {selectedBank}</h2>
              <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Plaid Sandbox Credentials Required</p>
            </div>

            <div style={{ background: 'rgba(245, 158, 11, 0.1)', border: '1px solid rgba(245, 158, 11, 0.2)', padding: '0.75rem', borderRadius: '8px', marginBottom: '1.25rem', fontSize: '0.75rem', color: 'var(--color-warning)' }}>
              <strong>Sandbox Hint:</strong> Enter username <code>user_good</code> and password <code>mfa_device</code> to authorize.
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem', marginBottom: '1.5rem' }}>
              <div>
                <label style={{ display: 'block', fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '0.35rem', fontWeight: 500 }}>Username</label>
                <input
                  type="text"
                  placeholder="e.g. user_good"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  className="filter-input"
                  style={{ width: '100%', padding: '0.75rem' }}
                  required
                />
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '0.8rem', color: 'var(--text-secondary)', marginBottom: '0.35rem', fontWeight: 500 }}>Password</label>
                <input
                  type="password"
                  placeholder="e.g. mfa_device"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="filter-input"
                  style={{ width: '100%', padding: '0.75rem' }}
                  required
                />
              </div>
            </div>

            <div style={{ display: 'flex', gap: '0.5rem' }}>
              <button 
                type="button" 
                onClick={() => setStep(1)} 
                className="btn btn-secondary" 
                style={{ flex: 1 }}
              >
                Back
              </button>
              <button 
                type="submit" 
                className="btn btn-primary" 
                style={{ flex: 2 }}
              >
                Authorize Link
              </button>
            </div>
          </form>
        )}

        {step === 3 && (
          <div style={{ textAlign: 'center', padding: '2rem 1rem' }}>
            <div style={{ marginBottom: '1.5rem' }}>
              <Loader2 className="spinning" size={48} style={{ color: 'var(--color-primary)', animation: 'spin 1.5s linear infinite' }} />
            </div>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 700, marginBottom: '0.5rem' }}>Connecting to {selectedBank}...</h3>
            <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
              Retrieving accounts and authorization tokens. Auto-syncing bank feed transactions into your database.
            </p>
            <style>{`
              @keyframes spin {
                from { transform: rotate(0deg); }
                to { transform: rotate(360deg); }
              }
            `}</style>
          </div>
        )}
      </div>
    </div>
  );
};
