// frontend/src/app/components/transaction-list/transaction-list.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { Transaction, TransactionFilters } from '../../models/transaction.model';
import { lastValueFrom } from 'rxjs';

@Component({
  selector: 'app-transaction-list',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './transaction-list.component.html'
})
export class TransactionListComponent implements OnChanges {
  @Input() transactions: Transaction[] = [];
  @Input() filters: TransactionFilters = { search: '', category: 'All', anomalyOnly: false };
  @Input() linkedBanks: string[] = [];
  @Output() filtersChange = new EventEmitter<TransactionFilters>();
  @Output() refresh = new EventEmitter<void>();
  @Output() openPlaid = new EventEmitter<void>();

  showAddForm = signal(false);
  newDesc = signal('');
  newAmount = signal('');
  newDate = signal(new Date().toISOString().split('T')[0]);
  newCategory = signal('Uncategorized');
  newType = signal<'CREDIT' | 'DEBIT'>('DEBIT');
  selectedBank = signal('');
  isSubmitting = signal(false);

  categories = ['All', 'Dining', 'Grocery', 'Transportation', 'Rent', 'Bills', 'Shopping', 'Entertainment', 'Income', 'Medical', 'Uncategorized'];
  categoriesForForm = ['Dining', 'Grocery', 'Transportation', 'Rent', 'Bills', 'Shopping', 'Entertainment', 'Income', 'Medical', 'Uncategorized'];

  constructor(private api: ApiService) {}

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['linkedBanks']) {
      if (this.linkedBanks.length > 0 && !this.selectedBank()) {
        this.selectedBank.set(this.linkedBanks[0]);
      }
    }
  }

  updateSearch(value: string): void {
    this.filtersChange.emit({ ...this.filters, search: value });
  }

  updateCategory(value: string): void {
    this.filtersChange.emit({ ...this.filters, category: value });
  }

  updateAnomalyOnly(checked: boolean): void {
    this.filtersChange.emit({ ...this.filters, anomalyOnly: checked });
  }

  onTypeChange(value: string): void {
    const type = value as 'CREDIT' | 'DEBIT';
    this.newType.set(type);
    if (type === 'CREDIT') {
      this.newCategory.set('Income');
    } else if (this.newCategory() === 'Income') {
      this.newCategory.set('Uncategorized');
    }
  }

  async handleAddSubmit(e: Event): Promise<void> {
    e.preventDefault();
    if (!this.newDesc() || !this.newAmount()) return;

    let bankName = 'Manual Entry';
    if (this.linkedBanks.length === 1) {
      bankName = this.linkedBanks[0];
    } else if (this.linkedBanks.length > 1) {
      bankName = this.selectedBank() || this.linkedBanks[0];
    } else {
      alert('Please link a bank feed first before adding manual transactions.');
      return;
    }

    this.isSubmitting.set(true);
    try {
      await lastValueFrom(this.api.addTransaction({
        amount: parseFloat(this.newAmount()),
        currency: 'INR',
        date: this.newDate(),
        description: this.newDesc(),
        category: this.newCategory(),
        bankName,
        accountName: 'Wallet',
        anomalyStatus: 'NONE',
        type: this.newType()
      }));
      this.newDesc.set('');
      this.newAmount.set('');
      this.newCategory.set('Uncategorized');
      this.newType.set('DEBIT');
      this.showAddForm.set(false);
      this.refresh.emit();
    } catch (err) {
      alert('Error creating transaction: ' + err);
    } finally {
      this.isSubmitting.set(false);
    }
  }

  async handleClearDatabase(): Promise<void> {
    if (window.confirm('Are you sure you want to clear the entire database? This cannot be undone.')) {
      try {
        await lastValueFrom(this.api.clearTransactions());
        this.refresh.emit();
      } catch (err) {
        alert('Error clearing transactions: ' + err);
      }
    }
  }

  isCredit(t: Transaction): boolean {
    return t.type === 'CREDIT' || (t.type === undefined && t.category === 'Income');
  }

  anomalyClass(status?: string): string {
    return status ? status.toLowerCase() : '';
  }

  anomalyLabel(status?: string): string {
    return status ? status.replace('_', ' ') : '';
  }
}

<div class="card" style="display:flex;flex-direction:column;gap:1.25rem;">
  <div style="display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:1rem;">
    <div>
      <h2 style="font-size:1.25rem;font-weight:700;">Transaction History</h2>
      <p style="font-size:0.8rem;color:var(--text-secondary);">Showing {{ transactions.length }} transactions</p>
    </div>
    <div style="display:flex;gap:0.5rem;">
      <button (click)="openPlaid.emit()" class="btn btn-primary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg>
        Connect Bank Feed
      </button>
      <button (click)="showAddForm.set(!showAddForm())" class="btn btn-secondary">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="M12 5v14"/></svg>
        Add Manual
      </button>
      <button (click)="handleClearDatabase()" class="btn btn-danger btn-icon" title="Clear All Transactions">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18"/><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/></svg>
      </button>
    </div>
  </div>

  <!-- Add Transaction Form -->
  @if (showAddForm()) {
    <form (ngSubmit)="handleAddSubmit($event)" style="background:rgba(15,23,42,0.4);border:1px solid var(--border-color);padding:1.25rem;border-radius:10px;animation:slideIn 0.25s ease-out;">
      <h3 style="font-size:0.95rem;font-weight:700;margin-bottom:0.75rem;color:var(--color-primary);">Add Transaction (AI will auto-categorize if left Uncategorized)</h3>

      @if (linkedBanks.length === 0) {
        <div style="background:rgba(239,68,68,0.1);border:1px solid rgba(239,68,68,0.2);padding:0.75rem 1rem;border-radius:8px;color:#f87171;font-size:0.85rem;margin-bottom:1rem;display:flex;align-items:center;gap:0.5rem;">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><path d="M12 9v4"/><path d="M12 17h.01"/></svg>
          <span>Please link a bank feed first before adding manual transactions.</span>
        </div>
      } @else {
        <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:0.75rem;margin-bottom:1rem;">
          <div>
            <label style="display:block;font-size:0.75rem;color:var(--text-secondary);margin-bottom:0.25rem;">Description</label>
            <input type="text" placeholder="e.g. Starbucks MG Road" [value]="newDesc()" (input)="newDesc.set($any($event.target).value)" class="filter-input" style="width:100%;padding:0.4rem 0.6rem;" required />
          </div>
          <div>
            <label style="display:block;font-size:0.75rem;color:var(--text-secondary);margin-bottom:0.25rem;">Amount (₹)</label>
            <input type="number" placeholder="e.g. 380" [value]="newAmount()" (input)="newAmount.set($any($event.target).value)" class="filter-input" style="width:100%;padding:0.4rem 0.6rem;" required />
          </div>
          <div>
            <label style="display:block;font-size:0.75rem;color:var(--text-secondary);margin-bottom:0.25rem;">Date</label>
            <input type="date" [value]="newDate()" (input)="newDate.set($any($event.target).value)" class="filter-input" style="width:100%;padding:0.4rem 0.6rem;" required />
          </div>
          <div>
            <label style="display:block;font-size:0.75rem;color:var(--text-secondary);margin-bottom:0.25rem;">Type</label>
            <select [value]="newType()" (change)="onTypeChange($any($event.target).value)" class="filter-input" style="width:100%;padding:0.4rem 0.6rem;background:var(--bg-secondary);">
              <option value="DEBIT">Debit (Expense)</option>
              <option value="CREDIT">Credit (Income/Refund)</option>
            </select>
          </div>
          <div>
            <label style="display:block;font-size:0.75rem;color:var(--text-secondary);margin-bottom:0.25rem;">Initial Category</label>
            <select [value]="newCategory()" (change)="newCategory.set($any($event.target).value)" class="filter-input" style="width:100%;padding:0.4rem 0.6rem;background:var(--bg-secondary);">
              @for (c of categoriesForForm; track c) {
                <option [value]="c">{{ c }}</option>
              }
            </select>
          </div>
          @if (linkedBanks.length > 1) {
            <div>
              <label style="display:block;font-size:0.75rem;color:var(--text-secondary);margin-bottom:0.25rem;">Link to Bank</label>
              <select [value]="selectedBank()" (change)="selectedBank.set($any($event.target).value)" class="filter-input" style="width:100%;padding:0.4rem 0.6rem;background:var(--bg-secondary);" required>
                @for (b of linkedBanks; track b) {
                  <option [value]="b">{{ b }}</option>
                }
              </select>
            </div>
          }
        </div>
      }

      <div style="display:flex;justify-content:flex-end;gap:0.5rem;">
        <button type="button" (click)="showAddForm.set(false)" class="btn btn-secondary" style="padding:0.4rem 0.8rem;font-size:0.8rem;">Cancel</button>
        <button type="submit" class="btn btn-primary" style="padding:0.4rem 1rem;font-size:0.8rem;" [disabled]="isSubmitting() || linkedBanks.length === 0">
          {{ isSubmitting() ? 'Saving...' : 'Save Transaction' }}
        </button>
      </div>
    </form>
  }

  <!-- Filters -->
  <div class="filter-bar">
    <div style="position:relative;flex:1 1 200px;">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--text-muted)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="position:absolute;left:0.75rem;top:50%;transform:translateY(-50%);"><circle cx="11" cy="11" r="8"/><path d="m21 21-4.3-4.3"/></svg>
      <input type="text" placeholder="Search by merchant or note..." [value]="filters.search || ''" (input)="updateSearch($any($event.target).value)" class="filter-input" style="width:100%;padding-left:2.25rem;" />
    </div>
    <select [value]="filters.category || 'All'" (change)="updateCategory($any($event.target).value)" class="filter-input" style="flex:1 1 120px;background:var(--bg-secondary);">
      @for (c of categories; track c) {
        <option [value]="c">{{ c }} Category</option>
      }
    </select>
    <div style="display:flex;align-items:center;gap:0.5rem;background:rgba(255,255,255,0.03);border:1px solid var(--border-color);padding:0.5rem 0.75rem;border-radius:8px;">
      <input type="checkbox" id="anomalyOnly" [checked]="filters.anomalyOnly || false" (change)="updateAnomalyOnly($any($event.target).checked)" style="cursor:pointer;" />
      <label for="anomalyOnly" style="font-size:0.8rem;color:var(--text-secondary);cursor:pointer;display:flex;align-items:center;gap:0.25rem;">
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="var(--color-warning)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><path d="M12 9v4"/><path d="M12 17h.01"/></svg>
        Anomalies Only
      </label>
    </div>
  </div>

  <!-- Transaction Table -->
  <div class="table-container">
    @if (transactions.length === 0) {
      <div style="text-align:center;padding:3rem 1rem;color:var(--text-muted);">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-bottom:0.75rem;opacity:0.5;"><path d="M2 20a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8l-7 5V8l-7 5V4a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2Z"/></svg>
        <p>No transactions found matching the current filters.</p>
        <p style="font-size:0.8rem;margin-top:0.25rem;">Try importing mock data or adding a transaction manually.</p>
      </div>
    } @else {
      <table class="transaction-table">
        <thead>
          <tr>
            <th>Date</th>
            <th>Description</th>
            <th>Category</th>
            <th>Source</th>
            <th>Amount</th>
            <th>Alerts</th>
          </tr>
        </thead>
        <tbody>
          @for (t of transactions; track t.id) {
            <tr class="transaction-row">
              <td style="font-size:0.85rem;color:var(--text-secondary);">
                <div style="display:flex;align-items:center;gap:0.35rem;">
                  <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="opacity:0.5;"><path d="M8 2v4"/><path d="M16 2v4"/><rect width="18" height="18" x="3" y="4" rx="2"/><path d="M3 10h18"/></svg>
                  {{ t.date }}
                </div>
              </td>
              <td>
                <div style="font-weight:600;">{{ t.description }}</div>
                @if (t.notes) {
                  <div style="font-size:0.75rem;color:var(--text-muted);margin-top:0.15rem;">{{ t.notes }}</div>
                }
              </td>
              <td>
                <span [class]="'category-badge ' + t.category.toLowerCase()">{{ t.category }}</span>
              </td>
              <td style="font-size:0.8rem;color:var(--text-secondary);">
                <div>{{ t.bankName || 'Wallet' }}</div>
                <div style="font-size:0.7rem;color:var(--text-muted);">{{ t.accountName || 'Cash' }}</div>
              </td>
              <td [style.color]="isCredit(t) ? 'var(--color-success)' : '#fff'" style="font-weight:700;">
                {{ isCredit(t) ? '+' : '-' }} ₹{{ t.amount.toLocaleString(undefined, {minimumFractionDigits: 2, maximumFractionDigits: 2}) }}
              </td>
              <td>
                @if (t.anomalyStatus && t.anomalyStatus !== 'NONE') {
                  <span [class]="'anomaly-tag ' + anomalyClass(t.anomalyStatus)" [title]="t.anomalyDescription || ''" style="cursor:help;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3Z"/><path d="M12 9v4"/><path d="M12 17h.01"/></svg>
                    {{ anomalyLabel(t.anomalyStatus) }}
                  </span>
                }
              </td>
            </tr>
          }
        </tbody>
      </table>
    }
  </div>
</div>

// frontend/src/components/TransactionList.tsx
import React, { useState, useEffect } from 'react';
import { Search, Plus, Calendar, AlertTriangle, Trash2, Layers } from 'lucide-react';
import { apiService } from '../services/api';
import type { Transaction, TransactionFilters } from '../services/api';

interface TransactionListProps {
  transactions: Transaction[];
  onRefresh: () => void;
  filters: TransactionFilters;
  setFilters: React.Dispatch<React.SetStateAction<TransactionFilters>>;
  onOpenPlaid: () => void;
  linkedBanks: string[];
}

export const TransactionList: React.FC<TransactionListProps> = ({
  transactions,
  onRefresh,
  filters,
  setFilters,
  onOpenPlaid,
  linkedBanks
}) => {
  const [showAddForm, setShowAddForm] = useState(false);
  const [newDesc, setNewDesc] = useState('');
  const [newAmount, setNewAmount] = useState('');
  const [newDate, setNewDate] = useState(new Date().toISOString().split('T')[0]);
  const [newCategory, setNewCategory] = useState('Uncategorized');
  const [selectedBank, setSelectedBank] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);

  useEffect(() => {
    if (linkedBanks.length > 0 && !selectedBank) {
      setSelectedBank(linkedBanks[0]);
    }
  }, [linkedBanks, selectedBank]);

  const categories = ['All', 'Dining', 'Grocery', 'Transportation', 'Rent', 'Bills', 'Shopping', 'Entertainment', 'Income', 'Medical', 'Uncategorized'];

  const handleAddSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newDesc || !newAmount) return;

    let bankName = 'Manual Entry';
    if (linkedBanks.length === 1) {
      bankName = linkedBanks[0];
    } else if (linkedBanks.length > 1) {
      bankName = selectedBank || linkedBanks[0];
    } else {
      alert('Please link a bank feed first before adding manual transactions.');
      return;
    }

    setIsSubmitting(true);
    try {
      await apiService.addTransaction({
        amount: parseFloat(newAmount),
        currency: 'INR',
        date: newDate,
        description: newDesc,
        category: newCategory,
        bankName: bankName,
        accountName: 'Wallet',
        anomalyStatus: 'NONE'
      });
      // Reset form
      setNewDesc('');
      setNewAmount('');
      setNewCategory('Uncategorized');
      setShowAddForm(false);
      onRefresh();
    } catch (err) {
      alert('Error creating transaction: ' + err);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleClearDatabase = async () => {
    if (window.confirm('Are you sure you want to clear the entire database? This cannot be undone.')) {
      try {
        await apiService.clearTransactions();
        onRefresh();
      } catch (err) {
        alert('Error clearing transactions: ' + err);
      }
    }
  };

  return (
    <div className="card" style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h2 style={{ fontSize: '1.25rem', fontWeight: 700 }}>Transaction History</h2>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
            Showing {transactions.length} transactions
          </p>
        </div>

        <div style={{ display: 'flex', gap: '0.5rem' }}>
          <button onClick={onOpenPlaid} className="btn btn-primary">
            <Plus size={16} /> Connect Bank Feed
          </button>
          <button 
            onClick={() => setShowAddForm(!showAddForm)} 
            className="btn btn-secondary"
          >
            <Plus size={16} /> Add Manual
          </button>
          <button 
            onClick={handleClearDatabase} 
            className="btn btn-danger btn-icon"
            title="Clear All Transactions"
          >
            <Trash2 size={16} />
          </button>
        </div>
      </div>

      {/* Expandable Manual Form */}
      {showAddForm && (
        <form 
          onSubmit={handleAddSubmit} 
          style={{ 
            background: 'rgba(15, 23, 42, 0.4)', 
            border: '1px solid var(--border-color)', 
            padding: '1.25rem', 
            borderRadius: '10px',
            animation: 'slideIn 0.25s ease-out' 
          }}
        >
          <h3 style={{ fontSize: '0.95rem', fontWeight: 700, marginBottom: '0.75rem', color: 'var(--color-primary)' }}>
            Add Transaction (AI will auto-categorize if left Uncategorized)
          </h3>
          {linkedBanks.length === 0 ? (
            <div 
              style={{ 
                background: 'rgba(239, 68, 68, 0.1)', 
                border: '1px solid rgba(239, 68, 68, 0.2)', 
                padding: '0.75rem 1rem', 
                borderRadius: '8px', 
                color: '#f87171', 
                fontSize: '0.85rem',
                marginBottom: '1rem',
                display: 'flex',
                alignItems: 'center',
                gap: '0.5rem'
              }}
            >
              <AlertTriangle size={16} />
              <span>Please link a bank feed first before adding manual transactions.</span>
            </div>
          ) : (
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(180px, 1fr))', gap: '0.75rem', marginBottom: '1rem' }}>
              <div>
                <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Description</label>
                <input
                  type="text"
                  placeholder="e.g. Starbucks MG Road"
                  value={newDesc}
                  onChange={(e) => setNewDesc(e.target.value)}
                  className="filter-input"
                  style={{ width: '100%', padding: '0.4rem 0.6rem' }}
                  required
                />
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Amount (₹)</label>
                <input
                  type="number"
                  placeholder="e.g. 380"
                  value={newAmount}
                  onChange={(e) => setNewAmount(e.target.value)}
                  className="filter-input"
                  style={{ width: '100%', padding: '0.4rem 0.6rem' }}
                  required
                />
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Date</label>
                <input
                  type="date"
                  value={newDate}
                  onChange={(e) => setNewDate(e.target.value)}
                  className="filter-input"
                  style={{ width: '100%', padding: '0.4rem 0.6rem' }}
                  required
                />
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Initial Category</label>
                <select
                  value={newCategory}
                  onChange={(e) => setNewCategory(e.target.value)}
                  className="filter-input"
                  style={{ width: '100%', padding: '0.4rem 0.6rem', background: '#0f172a' }}
                >
                  {categories.slice(1).map(c => (
                    <option key={c} value={c}>{c}</option>
                  ))}
                </select>
              </div>

              {linkedBanks.length > 1 && (
                <div>
                  <label style={{ display: 'block', fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.25rem' }}>Link to Bank</label>
                  <select
                    value={selectedBank}
                    onChange={(e) => setSelectedBank(e.target.value)}
                    className="filter-input"
                    style={{ width: '100%', padding: '0.4rem 0.6rem', background: '#0f172a' }}
                    required
                  >
                    {linkedBanks.map(b => (
                      <option key={b} value={b}>{b}</option>
                    ))}
                  </select>
                </div>
              )}
            </div>
          )}

          <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '0.5rem' }}>
            <button type="button" onClick={() => setShowAddForm(false)} className="btn btn-secondary" style={{ padding: '0.4rem 0.8rem', fontSize: '0.8rem' }}>
              Cancel
            </button>
            <button type="submit" className="btn btn-primary" style={{ padding: '0.4rem 1rem', fontSize: '0.8rem' }} disabled={isSubmitting || linkedBanks.length === 0}>
              {isSubmitting ? 'Saving...' : 'Save Transaction'}
            </button>
          </div>
        </form>
      )}

      {/* Filter Options */}
      <div className="filter-bar">
        <div style={{ position: 'relative', flex: '1 1 200px' }}>
          <Search size={16} style={{ position: 'absolute', left: '0.75rem', top: '50%', transform: 'translateY(-50%)', color: 'var(--text-muted)' }} />
          <input
            type="text"
            placeholder="Search by merchant or note..."
            value={filters.search || ''}
            onChange={(e) => setFilters(prev => ({ ...prev, search: e.target.value }))}
            className="filter-input"
            style={{ width: '100%', paddingLeft: '2.25rem' }}
          />
        </div>

        <select
          value={filters.category || 'All'}
          onChange={(e) => setFilters(prev => ({ ...prev, category: e.target.value }))}
          className="filter-input"
          style={{ flex: '1 1 120px', background: '#0f172a' }}
        >
          {categories.map(c => (
            <option key={c} value={c}>{c} Category</option>
          ))}
        </select>

        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', background: 'rgba(255,255,255,0.03)', border: '1px solid var(--border-color)', padding: '0.5rem 0.75rem', borderRadius: '8px' }}>
          <input
            type="checkbox"
            id="anomalyOnly"
            checked={filters.anomalyOnly || false}
            onChange={(e) => setFilters(prev => ({ ...prev, anomalyOnly: e.target.checked }))}
            style={{ cursor: 'pointer' }}
          />
          <label htmlFor="anomalyOnly" style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
            <AlertTriangle size={14} style={{ color: 'var(--color-warning)' }} /> Anomalies Only
          </label>
        </div>
      </div>

      {/* Transactions Grid/Table */}
      <div className="table-container">
        {transactions.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '3rem 1rem', color: 'var(--text-muted)' }}>
            <Layers size={40} style={{ marginBottom: '0.75rem', opacity: 0.5 }} />
            <p>No transactions found matching the current filters.</p>
            <p style={{ fontSize: '0.8rem', marginTop: '0.25rem' }}>Try importing mock data or adding a transaction manually.</p>
          </div>
        ) : (
          <table className="transaction-table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Category</th>
                <th>Source</th>
                <th>Amount</th>
                <th>Alerts</th>
              </tr>
            </thead>
            <tbody>
              {transactions.map((t) => (
                <tr key={t.id} className="transaction-row">
                  <td style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
                      <Calendar size={14} style={{ opacity: 0.5 }} />
                      {t.date}
                    </div>
                  </td>
                  <td>
                    <div style={{ fontWeight: 600 }}>{t.description}</div>
                    {t.notes && <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', marginTop: '0.15rem' }}>{t.notes}</div>}
                  </td>
                  <td>
                    <span className={`category-badge ${t.category.toLowerCase()}`}>
                      {t.category}
                    </span>
                  </td>
                  <td style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>
                    <div>{t.bankName || 'Wallet'}</div>
                    <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>{t.accountName || 'Cash'}</div>
                  </td>
                  <td style={{ fontWeight: 700, color: t.category === 'Income' ? 'var(--color-success)' : '#fff' }}>
                    {t.category === 'Income' ? '+' : '-'} ₹{t.amount?.toLocaleString()}
                  </td>
                  <td>
                    {t.anomalyStatus && t.anomalyStatus !== 'NONE' && (
                      <span 
                        className={`anomaly-tag ${t.anomalyStatus.toLowerCase()}`}
                        title={t.anomalyDescription}
                        style={{ cursor: 'help' }}
                      >
                        <AlertTriangle size={12} /> {t.anomalyStatus.replace('_', ' ')}
                      </span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
};
