// frontend/src/components/ChatAssistant.tsx
import { useState, useRef, useEffect } from 'react';
import { Send, Sparkles, X } from 'lucide-react';
import { apiService } from '../services/api';

interface Message {
  sender: 'user' | 'assistant';
  text: string;
  time: string;
}

interface ChatAssistantProps {
  onClose?: () => void;
}

export const ChatAssistant: React.FC<ChatAssistantProps> = ({ onClose }) => {
  const [messages, setMessages] = useState<Message[]>([
    {
      sender: 'assistant',
      text: "Hello! I am **FinVertex**. I can search, analyze, and monitor your transactions.\n\nAsk me questions like:\n* *'Show me all transactions over ₹5000 last week.'*\n* *'Do I have any duplicate charges?'*\n* *'Tell me what I spent on dining this month.'*",
      time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
    }
  ]);
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isLoading]);

  const handleSend = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userText = input;
    setInput('');
    const time = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    setMessages((prev) => [...prev, { sender: 'user', text: userText, time }]);
    setIsLoading(true);

    try {
      const responseText = await apiService.sendChatMessage(userText);
      setMessages((prev) => [
        ...prev,
        {
          sender: 'assistant',
          text: responseText || "I couldn't process that query.",
          time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        }
      ]);
    } catch (err: any) {
      setMessages((prev) => [
        ...prev,
        {
          sender: 'assistant',
          text: `⚠️ **Error connecting to AI Server:** ${err.message}. Make sure your backend application is running and your OpenAI API key is configured.`,
          time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
        }
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleQuickPrompt = (promptText: string) => {
    setInput(promptText);
  };

  // Basic custom markdown parser for chatbot bubbles
  const renderMessageContent = (text: string) => {
    // Escape simple HTML
    let html = text
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");

    // Bold tags
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    
    // Italic tags
    html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');

    // Handle Tables
    const lines = html.split('\n');
    let inTable = false;
    let tableHtml = '';
    const outputLines: string[] = [];

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      
      // Is it a table row?
      if (line.startsWith('|') && line.endsWith('|')) {
        if (!inTable) {
          inTable = true;
          tableHtml = '<table>';
        }
        
        // Skip separator line |---|---|
        if (line.includes('---') || line.includes('-:-')) {
          continue;
        }

        const cells = line.split('|').slice(1, -1).map(c => c.trim());
        const isHeader = !tableHtml.includes('<tbody>') && !tableHtml.includes('<thead>');
        
        if (isHeader) {
          tableHtml += '<thead><tr>' + cells.map(c => `<th>${c}</th>`).join('') + '</tr></thead><tbody>';
        } else {
          tableHtml += '<tr>' + cells.map(c => `<td>${c}</td>`).join('') + '</tr>';
        }
      } else {
        if (inTable) {
          inTable = false;
          tableHtml += '</tbody></table>';
          outputLines.push(tableHtml);
          tableHtml = '';
        }
        
        // Bullet list item
        if (line.startsWith('* ') || line.startsWith('- ')) {
          outputLines.push(`<li>${line.substring(2)}</li>`);
        } else if (line.startsWith('### ')) {
          outputLines.push(`<h3>${line.substring(4)}</h3>`);
        } else if (line.startsWith('## ')) {
          outputLines.push(`<h2>${line.substring(3)}</h2>`);
        } else if (line.startsWith('# ')) {
          outputLines.push(`<h1>${line.substring(2)}</h1>`);
        } else if (line) {
          outputLines.push(`<p>${line}</p>`);
        }
      }
    }

    if (inTable) {
      tableHtml += '</tbody></table>';
      outputLines.push(tableHtml);
    }

    // Wrap continuous li tags in a ul
    let finalHtml = '';
    let inList = false;
    
    for (const item of outputLines) {
      if (item.startsWith('<li>')) {
        if (!inList) {
          inList = true;
          finalHtml += '<ul>';
        }
        finalHtml += item;
      } else {
        if (inList) {
          inList = false;
          finalHtml += '</ul>';
        }
        finalHtml += item;
      }
    }
    if (inList) {
      finalHtml += '</ul>';
    }

    return <div dangerouslySetInnerHTML={{ __html: finalHtml }} />;
  };

  const quickPrompts = [
    "Do I have any duplicate charges?",
    "Show me transactions over ₹5000",
    "Categorize Swiggy to Dining",
    "Analyze my weekend spending"
  ];

  return (
    <div className="chat-widget">
      <div className="chat-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', width: '100%' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <div className="chat-header-status"></div>
          <div style={{ display: 'flex', flexDirection: 'column' }}>
            <span style={{ fontSize: '0.9rem', fontWeight: 700, display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
              FinVertex <Sparkles size={13} style={{ color: 'var(--color-accent)' }} />
            </span>
            <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>Spring AI Function Calling Agent</span>
          </div>
        </div>
        {onClose && (
          <button onClick={onClose} className="chat-close-btn" aria-label="Close Chat">
            <X size={18} />
          </button>
        )}
      </div>

      <div className="chat-messages">
        {messages.map((msg, index) => (
          <div key={index} className={`chat-message ${msg.sender}`}>
            <div className="message-bubble">
              {renderMessageContent(msg.text)}
            </div>
            <span className="message-time">{msg.time}</span>
          </div>
        ))}
        {isLoading && (
          <div className="chat-message assistant">
            <div className="message-bubble" style={{ padding: '0.5rem' }}>
              <div className="ai-typing-indicator">
                <div className="typing-dot"></div>
                <div className="typing-dot"></div>
                <div className="typing-dot"></div>
              </div>
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      <div style={{ padding: '0.5rem 1rem', display: 'flex', flexWrap: 'wrap', gap: '0.35rem', borderTop: '1px solid var(--border-color)', background: 'rgba(15, 23, 42, 0.15)' }}>
        {quickPrompts.map((p, idx) => (
          <button
            key={idx}
            onClick={() => handleQuickPrompt(p)}
            className="filter-input"
            style={{ fontSize: '0.75rem', padding: '0.25rem 0.5rem', cursor: 'pointer', borderRadius: '20px', border: '1px solid rgba(255,255,255,0.08)' }}
          >
            {p}
          </button>
        ))}
      </div>

      <form onSubmit={handleSend} className="chat-input-form">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="Ask AI (e.g. 'what did I spend on cafes last week?')..."
          className="chat-input"
          disabled={isLoading}
        />
        <button type="submit" className="btn btn-primary" style={{ padding: '0.75rem' }} disabled={isLoading}>
          <Send size={18} />
        </button>
      </form>
    </div>
  );
};

// frontend/src/app/components/chat-assistant/chat-assistant.component.ts
import { Component, Output, EventEmitter, OnInit, signal, ViewChild, ElementRef, AfterViewChecked, ChangeDetectionStrategy } from '@angular/core';

import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { lastValueFrom } from 'rxjs';

interface ChatMessage {
  sender: 'user' | 'assistant';
  text: string;
  time: string;
  html?: string;
}

@Component({
    selector: 'app-chat-assistant',
    imports: [FormsModule],
    changeDetection: ChangeDetectionStrategy.Eager,
    templateUrl: './chat-assistant.component.html'
})
export class ChatAssistantComponent implements OnInit, AfterViewChecked {
  @Output() closeChat = new EventEmitter<void>();
  @ViewChild('messagesEnd') messagesEndRef!: ElementRef;

  messages = signal<ChatMessage[]>([]);
  input = signal('');
  isLoading = signal(false);
  private shouldScroll = false;

  quickPrompts = [
    "Do I have any duplicate charges?",
    "Show me transactions over ₹5000",
    "Categorize Swiggy to Dining",
    "Analyze my weekend spending"
  ];

  constructor(private api: ApiService) {}

  ngOnInit(): void {
    const initTime = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    const welcomeText = "Hello! I am **FinVertex**. I can search, analyze, and monitor your transactions.\n\nAsk me questions like:\n* *'Show me all transactions over ₹5000 last week.'*\n* *'Do I have any duplicate charges?'*\n* *'Tell me what I spent on dining this month.'*";
    this.messages.set([{
      sender: 'assistant',
      text: welcomeText,
      time: initTime,
      html: this.renderMarkdown(welcomeText)
    }]);
  }

  ngAfterViewChecked(): void {
    if (this.shouldScroll) {
      this.scrollToBottom();
      this.shouldScroll = false;
    }
  }

  scrollToBottom(): void {
    if (this.messagesEndRef?.nativeElement) {
      this.messagesEndRef.nativeElement.scrollIntoView({ behavior: 'smooth' });
    }
  }

  setInput(value: string): void { this.input.set(value); }

  handleQuickPrompt(prompt: string): void { this.input.set(prompt); }

  async handleSend(e?: Event): Promise<void> {
    if (e) e.preventDefault();
    if (!this.input().trim() || this.isLoading()) return;

    const userText = this.input();
    this.input.set('');
    const time = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });

    this.messages.update(msgs => [...msgs, { sender: 'user', text: userText, time, html: this.escapeHtml(userText) }]);
    this.isLoading.set(true);
    this.shouldScroll = true;

    try {
      const res = await lastValueFrom(this.api.sendChatMessage(userText));
      const responseText = res.response || "I couldn't process that query.";
      this.messages.update(msgs => [...msgs, {
        sender: 'assistant',
        text: responseText,
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        html: this.renderMarkdown(responseText)
      }]);
    } catch (err: any) {
      const errMsg = `⚠️ **Error connecting to AI Server:** ${err.message}. Make sure your backend application is running and your OpenAI API key is configured.`;
      this.messages.update(msgs => [...msgs, {
        sender: 'assistant',
        text: errMsg,
        time: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        html: this.renderMarkdown(errMsg)
      }]);
    } finally {
      this.isLoading.set(false);
      this.shouldScroll = true;
    }
  }

  escapeHtml(text: string): string {
    return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  }

  renderMarkdown(text: string): string {
    let html = text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
    html = html.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/\*(.*?)\*/g, '<em>$1</em>');

    const lines = html.split('\n');
    let inTable = false;
    let tableHtml = '';
    const outputLines: string[] = [];

    for (const line of lines) {
      const l = line.trim();
      if (l.startsWith('|') && l.endsWith('|')) {
        if (!inTable) { inTable = true; tableHtml = '<table>'; }
        if (l.includes('---') || l.includes('-:-')) continue;
        const cells = l.split('|').slice(1, -1).map(c => c.trim());
        const isHeader = !tableHtml.includes('<tbody>') && !tableHtml.includes('<thead>');
        if (isHeader) {
          tableHtml += '<thead><tr>' + cells.map(c => `<th>${c}</th>`).join('') + '</tr></thead><tbody>';
        } else {
          tableHtml += '<tr>' + cells.map(c => `<td>${c}</td>`).join('') + '</tr>';
        }
      } else {
        if (inTable) { inTable = false; tableHtml += '</tbody></table>'; outputLines.push(tableHtml); tableHtml = ''; }
        if (l.startsWith('* ') || l.startsWith('- ')) outputLines.push(`<li>${l.substring(2)}</li>`);
        else if (l.startsWith('### ')) outputLines.push(`<h3>${l.substring(4)}</h3>`);
        else if (l.startsWith('## ')) outputLines.push(`<h2>${l.substring(3)}</h2>`);
        else if (l.startsWith('# ')) outputLines.push(`<h1>${l.substring(2)}</h1>`);
        else if (l) outputLines.push(`<p>${l}</p>`);
      }
    }
    if (inTable) { tableHtml += '</tbody></table>'; outputLines.push(tableHtml); }

    let finalHtml = '';
    let inList = false;
    for (const item of outputLines) {
      if (item.startsWith('<li>')) {
        if (!inList) { inList = true; finalHtml += '<ul>'; }
        finalHtml += item;
      } else {
        if (inList) { inList = false; finalHtml += '</ul>'; }
        finalHtml += item;
      }
    }
    if (inList) finalHtml += '</ul>';
    return finalHtml;
  }
}

<div class="chat-widget">
  <div class="chat-header" style="display:flex;justify-content:space-between;align-items:center;width:100%;">
    <div style="display:flex;align-items:center;gap:0.75rem;">
      <div class="chat-header-status"></div>
      <div style="display:flex;flex-direction:column;">
        <span style="font-size:0.9rem;font-weight:700;display:flex;align-items:center;gap:0.25rem;">
          FinVertex
          <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="var(--color-accent)" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z"/></svg>
        </span>
        <span style="font-size:0.7rem;color:var(--text-muted);">Spring AI Function Calling Agent</span>
      </div>
    </div>
    <button (click)="closeChat.emit()" class="chat-close-btn" aria-label="Close Chat">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
    </button>
  </div>

  <div class="chat-messages">
    @for (msg of messages(); track $index) {
      <div [class]="'chat-message ' + msg.sender">
        <div class="message-bubble" [innerHTML]="msg.html || msg.text"></div>
        <span class="message-time">{{ msg.time }}</span>
      </div>
    }
    @if (isLoading()) {
      <div class="chat-message assistant">
        <div class="message-bubble" style="padding:0.5rem;">
          <div class="ai-typing-indicator">
            <div class="typing-dot"></div>
            <div class="typing-dot"></div>
            <div class="typing-dot"></div>
          </div>
        </div>
      </div>
    }
    <div #messagesEnd></div>
  </div>

  <!-- Quick Prompts -->
  <div style="padding:0.5rem 1rem;display:flex;flex-wrap:wrap;gap:0.35rem;border-top:1px solid var(--border-color);background:rgba(15,23,42,0.15);">
    @for (p of quickPrompts; track p) {
      <button (click)="handleQuickPrompt(p)" class="filter-input"
        style="font-size:0.75rem;padding:0.25rem 0.5rem;cursor:pointer;border-radius:20px;border:1px solid rgba(255,255,255,0.08);">
        {{ p }}
      </button>
    }
  </div>

  <!-- Chat Input -->
  <form (ngSubmit)="handleSend($event)" class="chat-input-form">
    <input type="text" [value]="input()" (input)="setInput($any($event.target).value)"
      placeholder="Ask AI (e.g. 'what did I spend on cafes last week?')..."
      class="chat-input" [disabled]="isLoading()" />
    <button type="submit" class="btn btn-primary" style="padding:0.75rem;" [disabled]="isLoading()">
      <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m22 2-7 20-4-9-9-4Z"/><path d="M22 2 11 13"/></svg>
    </button>
  </form>
</div>
